### ISSUE TITLE
Error when reading PSDs created with Autodesk Sketchbook

### ISSUE THREAD

**Issue by audionerd** [Agamnentzar/ag-psd#32]
Here's an example PSD from Sketchbook with the issue:

[board-1-KHXDX.zip](https://github.com/Agamnentzar/ag-psd/files/5157250/board-1-KHXDX.zip)

Error is:
```
10:19:20.640 › Error: Invalid RLE data: exceeded buffer size 32/32
    at readDataRLE (…/ag-psd/dist/psdReader.js:577:31)
    at readData (…/ag-psd/dist/psdReader.js:427:9)
    at readLayerChannelImageData (…/ag-psd/dist/psdReader.js:403:13)
    at …/ag-psd/dist/psdReader.js:244:17
    at readSection (…/ag-psd/dist/psdReader.js:591:18)
    at readLayerInfo (…/ag-psd/dist/psdReader.js:229:5)
    at …/ag-psd/dist/psdReader.js:194:23
    at readSection (…/ag-psd/dist/psdReader.js:591:18)
    at Object.readPsd (…/ag-psd/dist/psdReader.js:193:5)
    at readPsd (…/ag-psd/dist/index.js:25:24)
```

Although my guess is this is a problem with the Autodesk Sketchbook exporter, and not with `ag-psd`.

**Comment by Agamnentzar** [comment]
I opened the file in Photoshop just fine, so might be issue with ag-psd

Is it supposed to only have image data on "Background" layer and have all other layers empty ?

**Comment by audionerd** [comment]
Yeah the other layers are intentionally empty (they are placeholders for named Storyboarder layers in this case).

**Comment by Agamnentzar** [comment]
Release version `11.1.3` with fixed RLE decompression

**Comment by audionerd** [comment]
Looks great! Thanks for the incredibly fast response!
